sudo: enabled

language: generic

branches:
  only:
    - master

git:
  submodules: false
  
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

      
before_install:
  - sudo apt update
  - sudo apt install -y linux-headers-$(uname -r)
  - sudo apt install -y build-essential libtool automake tree dkms
  - git clone https://github.com/icshwi/etherlabmaster
  
install:
  - cd etherlabmaster
  - echo "ETHERCAT_MASTER0=ens4" > ethercatmaster.local
  - make init
  - make showopts
  - make build
  - make install
  - tree /opt/etherlab/
  - make dkms_add
  - make dkms_build
  - make dkms_install
  - make setup
#  - echo "WITH_PATCHSET=YES" >> configure/CONFIG_OPTIONS.local
#  - make patchset
#  - make showopts
#  - make build
#  - make install
#  - tree /opt/etherlab/
  
after_success:
  - sudo systemctl start ethercat
  - sudo ethercat
  - sudo ethercat master


