sudo: enabled

dist: xenial

language: generic

branches:
  only:
    - master

git:
  submodules: false
  
matrix:
  include:
    - os: linux
      dist: xenial
#    - os: linux
#      dist: bionic

      
before_install:
  - sudo apt-get -qq update  > /dev/null 2>&1 
  - sudo apt-get install -y linux-headers-$(uname -r)   > /dev/null 2>&1 
  - sudo apt-get install -y build-essential realpath libtool automake tree screen mercurial dkms  > /dev/null 2>&1 
  - git clone https://github.com/icshwi/etherlabmaster
  
install:
  - cd etherlabmaster
  - echo "ETHERCAT_MASTER0=ens4" > ethercatmaster.local
  - make init
  - make showopts
  - make build
  - make install
  - tree /opt/etherlab/
  - make dkms_add
  - make dkms_build
  - make dkms_install
  - make setup
#  - echo "WITH_PATCHSET=YES" >> configure/CONFIG_OPTIONS.local
#  - make patchset
#  - make showopts
#  - make build
#  - make install
#  - tree /opt/etherlab/
  
after_success:
  - sudo systemctl start ethercat
  - ethercat master


