name: CI

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, ubuntu-16.04 ]
    
    steps:
    - name: Install the packages for the etherlabmaster
      run: |
        sudo apt update
        sudo apt install -y linux-headers-$(uname -r) build-essential libtool automake tree dkms
    - uses: actions/checkout@v1
    - name: Install the userspace library
      run: |
        echo "ETHERCAT_MASTER0=eth0" > ethercatmaster.local
        make init
        make showopts
        make build
        make install
        tree /opt/etherlab/
    - name: DKMS configuration
      run: |
        make dkms_install
        make dkms_build
        make dkms_install
        make setup
    - name: Run the ethercat master
      run: |
        sudo systemctl start ethercat
        sudo ethercat
        sudo ethercat master
